fiks har loget inn nivaa 4 for test
navikt/veilarbperson pull request #55
Opened 2020-10-22 11:06 UTC by hakonph

2020-10-22 12:17 UTC, AlexGaard requested changes

2020-10-22 12:17 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/difi/AccessTokenRepository.java
> +    public String refreshAccessToken() {
Tror dette kan forenkles litt.

```
    private volatile String difiAccessToken;

    public synchronized String getDifiAccessToken() {
        boolean isExpiredOrMissing = Optional.ofNullable(difiAccessToken)
                .map(tokenStr -> {
                    try {
                        return JWTParser.parse(tokenStr);
                    } catch (ParseException e) {
                        // TODO: Log
                        return null;
                    }
                })
                .map(jwtToken -> TokenUtils.expiresWithin(jwtToken, 1000 * 60))
                .orElse(true);

        if (isExpiredOrMissing) {
            difiAccessToken = fetchAccessToken();
        }

        return difiAccessToken;
    }

    public String fetchAccessToken() {
        return "New token";
    }

```

2020-10-22 12:18 UTC, hakonph commented on src/main/java/no/nav/veilarbperson/client/difi/AccessTokenAuthenticator.java
> +public class AccessTokenAuthenticator implements Authenticator {
Hvis tokent har utløpt vil denen prøve på nytt.
Vill ikke nødvendigvis hente nyt token per request

2020-10-23 07:20 UTC, theahj commented on src/main/java/no/nav/veilarbperson/config/ClientConfig.java
> +            log.error("fant ikke sps_passord");
Skal fikses når alt er klart for prod. Ref todo over

2020-10-23 08:23 UTC, AlexGaard requested changes

2020-10-23 08:23 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/difi/DifiClientImpl.java
> +    public DifiClientImpl(DifiAccessTokenProvider difiAccessTokenProvider, String xNavApikey, String difiUrl) {
Jeg ville kanskje heller brukt `Supplier<String>` eller et custom interface istedenfor å være avhengig av `DifiAccessTokenProvider`

2020-10-23 08:23 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/difi/DifiAccessTokenProvider.java
> +        synchronized (this) {
Jeg syntes at 
```
private volatile String difiAccessToken;

    public synchronized String getDifiAccessToken() {
        boolean isExpiredOrMissing = Optional.ofNullable(difiAccessToken)
                .map(tokenStr -> {
                    try {
                        return JWTParser.parse(tokenStr);
                    } catch (ParseException e) {
                        // TODO: Log
                        return null;
                    }
                })
                .map(jwtToken -> TokenUtils.expiresWithin(jwtToken, 1000 * 60))
                .orElse(true);

        if (isExpiredOrMissing) {
            difiAccessToken = fetchAccessToken();
        }

        return difiAccessToken;
    }

    private String fetchAccessToken() {
        return "New token";
    }
```
er litt lettere å lese og flytter kompleksiteten med tråder ut fra funksjonen som egentlig kun burde hente access token. Funksjonaliteten er den samme, så det kan være slik som det er nå også 👍

2020-10-23 08:24 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/difi/DifiAccessTokenProvider.java
> +        synchronized (this) {
Kunne også tatt det et steg videre og flyttet expire sjekken ut i en egen funksjon

2020-10-23 10:54 UTC, AlexGaard approved these changes

2020-10-23 10:58 UTC, merged