Fo 3023 Hent forskjellige typer av adresser fra PDL og flette med beskrivelser fra kodeverk
navikt/veilarbperson pull request #83
Opened 2021-03-01 16:56 UTC by sneha-d-desai

- La fjernet variabler tilbake i PersonV2data da blir de brukt i visitkortet
- Hent liste av telefonnr fra PDL og legg telefonnr fra KRR i den liste. 
- Skrevet test for å sjekke om telefonliste fra PDL innholder telefonnr fra KRR. Hvis ikke så legger telefonnr fra KRR.
- Hent master av opplysninger fra PDL
- Hent forskjellige typer av adresser fra PDL og flette de med beskrivelser fra kodeverk
- Skrevet test for flettet beskrivelser(poststed, landkode, kommune) fra kodeverket i adressene

2021-03-02 08:32 UTC, AlexGaard requested changes

2021-03-02 08:32 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/pdl/domain/Adresse.java
> +     LocalDate gyldigFraOgMed;
Dataen som PDL returnerer inneholder tid, så LocalDateTime passer bedre

2021-03-02 08:32 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +    public List<Telefon> leggKrrTelefonNrIListe(String telefonNummerFraKrr, List<Telefon> telefonListe) {
```
public void leggKrrTelefonNrIListe(String telefonNummerFraKrr, List<Telefon> telefonListe) {
        boolean harIkkeTelefonFraKrr = telefonNummerFraKrr != null 
                && telefonListe.stream().noneMatch(t -> telefonNummerFraKrr.equals(t.getTelefonNr()));
        
        if (harIkkeTelefonFraKrr) {
            Telefon telefonNrFraKrr = new Telefon().setPrioritet(telefonListe.size()+1+"").setTelefonNr(telefonNummerFraKrr).setMaster("KRR");
            telefonListe.add(telefonNrFraKrr);
        }
    }
```

Ville forenklet det litt slik som vist ovenfor. F. eks så trenger vi ikke å returnere listen når vi endrer på den direkte.

2021-03-02 08:32 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +        List<Kontaktadresse> kontaktadresseList = personV2Data.getKontaktadresser();
Det er bedre å bruke stream().map() i dette tilfellet

2021-03-03 11:18 UTC, sneha-d-desai commented on src/main/java/no/nav/veilarbperson/client/pdl/domain/Adresse.java
> +     LocalDate gyldigFraOgMed;
Vi får data fra PDL api i json string format og vi gjør ikke noen endringer på det feltet etter det har fått i backend. So String format må være greit tenker jeg :) ellers det feiler i data parsing hvis det er annet format enn String.

2021-03-03 11:28 UTC, sneha-d-desai commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +    public List<Telefon> leggKrrTelefonNrIListe(String telefonNummerFraKrr, List<Telefon> telefonListe) {
Det ser ut pent å bruke noneMatch(). Jeg kaller denne funksjonen fra flettDigitalKontaktinformasjon() sånn personV2Data.setTelefon(leggKrrTelefonNrIListe(kontaktinfo.getMobiltelefonnummer(), personV2Data.getTelefon()));
Når vi endrer på den liste direkte da kanskje jeg trenger ikke å sette den opp igjen i PersonV2Data, ikke sant? I den tilfeller jeg må bare kalle leggKrrTelefonNrIListe(kontaktinfo.getMobiltelefonnummer(), personV2Data.getTelefon()) fra flettDigitalKontaktinformasjon(), ikke sant?

2021-03-03 11:30 UTC, sneha-d-desai commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +        List<Kontaktadresse> kontaktadresseList = personV2Data.getKontaktadresser();
Kan du gi et example det du tenker her?

2021-03-04 14:17 UTC, AlexGaard approved these changes

2021-03-04 14:42 UTC, merged