TK-80: La et ny endepunkt til å hente personnavn fra pdl
navikt/veilarbperson pull request #90
Opened 2021-03-31 09:33 UTC by sneha-d-desai

2021-03-31 10:49 UTC, AlexGaard requested changes

2021-03-31 10:49 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +        HentPdlPerson.PersonNavn personNavn = ofNullable(pdlClient.hentPersonNavn(fnr, userToken))
PersonNavn vil ikke være NULL, men den kan inneholde en tom liste. Så  man kan droppe sjekken på NULL og heller sjekke at listen ikke er tom. Hvis listen er tom så kan man kaste et 404 ResponseStatusException

2021-03-31 10:49 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/client/pdl/domain/PersonNavn.java
> +package no.nav.veilarbperson.client.pdl.domain;
Denne ligger i feil mappe. Siden denne klassen ikke direkte blir brukt av PDL, men blir brukt i PersonV2Controller så burde den ligge under no.nav.veilarbperson.domain. Egentlig så kunne man brukt PersonNavn som allerede ligger der hvis det er ingen som har bruk for feltet `forkortetNavn`, så kan man heller vurdere å lage en PersonNavnV2 hvis man trenger å ha ekstra informasjon fra PDL

2021-04-06 12:29 UTC, AlexGaard requested changes

2021-04-06 12:29 UTC, AlexGaard commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +        if(!personNavn.getNavn().isEmpty()) {
En grei konvensjon å følge i slike tilfeller er at `throw ...` burde ligge ovenfor `return ...`
F.eks:
```java
if (personNavn.getNavn().isEmpty()) {
     throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Fant ikke navn til person");
}

return PersonV2DataMapper.navnMapper(personNavn.getNavn());
``` 
Da blir koden litt lettere å lese :)

2021-04-06 12:31 UTC, sneha-d-desai commented on src/main/java/no/nav/veilarbperson/service/PersonV2Service.java
> +        if(!personNavn.getNavn().isEmpty()) {
Ok 👍

2021-04-06 12:52 UTC, AlexGaard approved these changes

2021-04-06 12:53 UTC, merged